// <auto-generated />
using System;
using AutoDijelovi1.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AutoDijelovi1.Migrations
{
    [DbContext(typeof(AutoDijelovi1Context))]
    [Migration("20190131173700_Migracija1")]
    partial class Migracija1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AutoDijelovi1.Models.Auto", b =>
                {
                    b.Property<int>("AutoID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Dio");

                    b.Property<DateTime>("GodinaProizvodnje");

                    b.Property<string>("NazivAuta");

                    b.Property<int>("SkladisteID");

                    b.HasKey("AutoID");

                    b.HasIndex("SkladisteID");

                    b.ToTable("Auto");
                });

            modelBuilder.Entity("AutoDijelovi1.Models.Skladiste", b =>
                {
                    b.Property<int>("SkladisteId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Lokacija");

                    b.Property<string>("NazivSkladista");

                    b.HasKey("SkladisteId");

                    b.ToTable("Skladiste");
                });

            modelBuilder.Entity("AutoDijelovi1.Models.Auto", b =>
                {
                    b.HasOne("AutoDijelovi1.Models.Skladiste", "Skladiste")
                        .WithMany("Auti")
                        .HasForeignKey("SkladisteID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
